//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPurchase
    {
        public long CustomerId { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public long PurchaseAmount { get; set; }
        public string ItemsPurchased { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
    }
}
